-- ================================================================================
-- CareCode Database Schema
-- MariaDB/MySQL DDL
-- Generated: 2025-11-02
-- ================================================================================

-- Drop existing tables (in reverse order of dependencies)
DROP TABLE IF EXISTS TBL_EMAIL_VERIFICATION_TOKEN;
DROP TABLE IF EXISTS care_facility_bookings;
DROP TABLE IF EXISTS TBL_CHAT_MESSAGES;
DROP TABLE IF EXISTS TBL_CHAT_SESSIONS;
DROP TABLE IF EXISTS TBL_NOTIFICATION_SETTINGS;
DROP TABLE IF EXISTS TBL_NOTIFICATION_TEMPLATES;
DROP TABLE IF EXISTS notification_preferences;
DROP TABLE IF EXISTS TBL_NOTIFICATION;
DROP TABLE IF EXISTS TBL_POLICY_DOCUMENTS;
DROP TABLE IF EXISTS TBL_POLICIES;
DROP TABLE IF EXISTS TBL_POLICY_CATEGORIES;
DROP TABLE IF EXISTS TBL_HEALTH_RECORD_ATTACHMENTS;
DROP TABLE IF EXISTS TBL_HEALTH_RECORD;
DROP TABLE IF EXISTS TBL_HOSPITAL_REVIEW;
DROP TABLE IF EXISTS TBL_HOSPITAL_LIKE;
DROP TABLE IF EXISTS TBL_HOSPITAL;
DROP TABLE IF EXISTS TBL_BOOKMARK;
DROP TABLE IF EXISTS TBL_POST_LIKE;
DROP TABLE IF EXISTS TBL_POST_TAGS;
DROP TABLE IF EXISTS TBL_TAG;
DROP TABLE IF EXISTS TBL_COMMENT;
DROP TABLE IF EXISTS TBL_POST;
DROP TABLE IF EXISTS TBL_REVIEWS;
DROP TABLE IF EXISTS TBL_CARE_FACILITIES;
DROP TABLE IF EXISTS TBL_CHILD;
DROP TABLE IF EXISTS TBL_USER;

-- ================================================================================
-- 1. User Domain Tables
-- ================================================================================

-- User Table
CREATE TABLE TBL_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL COMMENT '자동 생성된 사용자 ID',
    EMAIL VARCHAR(255) NOT NULL UNIQUE COMMENT '이메일 (고유)',
    PASSWORD VARCHAR(255) COMMENT '비밀번호 (OAuth 사용자는 NULL)',
    NAME VARCHAR(100) NOT NULL COMMENT '사용자명',
    PHONE_NUMBER VARCHAR(20) COMMENT '전화번호',
    BIRTH_DATE DATE COMMENT '생년월일',
    GENDER VARCHAR(20) COMMENT '성별 (MALE, FEMALE, OTHER)',
    ADDRESS VARCHAR(500) COMMENT '주소',
    LATITUDE DOUBLE COMMENT '위도',
    LONGITUDE DOUBLE COMMENT '경도',
    PROFILE_IMAGE_URL VARCHAR(500) COMMENT '프로필 이미지 URL',
    ROLE VARCHAR(50) NOT NULL COMMENT '역할 (PARENT, CAREGIVER, ADMIN, GUEST)',
    PROVIDER VARCHAR(50) COMMENT 'OAuth 제공자 (kakao, google, naver)',
    PROVIDER_ID VARCHAR(255) COMMENT 'OAuth 제공자의 사용자 ID',
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성 상태',
    EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE COMMENT '이메일 인증 여부',
    REGISTRATION_COMPLETED BOOLEAN NOT NULL DEFAULT FALSE COMMENT '가입 완료 여부',
    DELETED_AT DATETIME COMMENT '소프트 삭제 시간',
    LAST_LOGIN_AT DATETIME COMMENT '마지막 로그인 시간',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간',
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 시간',

    INDEX idx_email (EMAIL),
    INDEX idx_provider (PROVIDER, PROVIDER_ID),
    INDEX idx_role (ROLE),
    INDEX idx_is_active (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 테이블';

-- Child Table
CREATE TABLE TBL_CHILD (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL COMMENT '부모 사용자 ID',
    NAME VARCHAR(100) NOT NULL COMMENT '자녀명',
    AGE INT COMMENT '나이',
    GENDER VARCHAR(20) COMMENT '성별',
    BIRTH_DATE DATE COMMENT '생년월일',
    SPECIAL_NEEDS TEXT COMMENT '특별한 요구사항',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_user_id (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='자녀 테이블';

-- Notification Settings Table
CREATE TABLE TBL_NOTIFICATION_SETTINGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL UNIQUE COMMENT '사용자 ID (One-to-One)',
    POLICY_NOTIFICATION BOOLEAN DEFAULT TRUE COMMENT '정책 알림',
    FACILITY_NOTIFICATION BOOLEAN DEFAULT TRUE COMMENT '시설 알림',
    COMMUNITY_NOTIFICATION BOOLEAN DEFAULT TRUE COMMENT '커뮤니티 알림',
    CHATBOT_NOTIFICATION BOOLEAN DEFAULT TRUE COMMENT '챗봇 알림',
    EMAIL_NOTIFICATION BOOLEAN DEFAULT TRUE COMMENT '이메일 알림',
    PUSH_NOTIFICATION BOOLEAN DEFAULT TRUE COMMENT '푸시 알림',
    SMS_NOTIFICATION BOOLEAN DEFAULT FALSE COMMENT 'SMS 알림',
    QUIET_HOURS_START TIME COMMENT '조용한 시간 시작',
    QUIET_HOURS_END TIME COMMENT '조용한 시간 종료',
    QUIET_HOURS_ENABLED BOOLEAN DEFAULT FALSE COMMENT '조용한 시간 활성화',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사용자 알림 설정';

-- Email Verification Token Table
CREATE TABLE TBL_EMAIL_VERIFICATION_TOKEN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TOKEN VARCHAR(255) NOT NULL UNIQUE COMMENT '인증 토큰',
    EXPIRY_DATE DATETIME NOT NULL COMMENT '만료 날짜',
    USED BOOLEAN NOT NULL DEFAULT FALSE COMMENT '사용 여부',

    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_token (TOKEN),
    INDEX idx_user_id (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='이메일 인증 토큰';

-- ================================================================================
-- 2. Care Facility Domain Tables
-- ================================================================================

-- Care Facility Table
CREATE TABLE TBL_CARE_FACILITIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACILITY_CODE VARCHAR(100) NOT NULL UNIQUE COMMENT '시설 코드',
    NAME VARCHAR(200) NOT NULL COMMENT '시설명',
    FACILITY_TYPE VARCHAR(50) COMMENT '시설 유형 (DAYCARE, KINDERGARTEN, NURSERY, PLAYGROUP, FAMILY_CARE, OTHER)',
    CITY VARCHAR(100) COMMENT '도시',
    DISTRICT VARCHAR(100) COMMENT '지역',
    ADDRESS VARCHAR(500) COMMENT '주소',
    LATITUDE DOUBLE COMMENT '위도',
    LONGITUDE DOUBLE COMMENT '경도',
    PHONE VARCHAR(20) COMMENT '전화번호',
    EMAIL VARCHAR(255) COMMENT '이메일',
    WEBSITE VARCHAR(500) COMMENT '웹사이트',
    CAPACITY INT COMMENT '수용인원',
    CURRENT_ENROLLMENT INT COMMENT '현재 입소자 수',
    AVAILABLE_SPOTS INT COMMENT '가능한 자리 수',
    AGE_RANGE_MIN INT COMMENT '최소 나이',
    AGE_RANGE_MAX INT COMMENT '최대 나이',
    AGE_RANGE VARCHAR(100) COMMENT '나이 범위',
    OPERATING_HOURS VARCHAR(200) COMMENT '운영 시간',
    TUITION_FEE INT COMMENT '학비',
    ADDITIONAL_FEES TEXT COMMENT '추가 수수료',
    FACILITIES TEXT COMMENT '시설 내 편의시설',
    CURRICULUM TEXT COMMENT '커리큘럼',
    TEACHER_COUNT INT COMMENT '교사 수',
    STUDENT_TEACHER_RATIO VARCHAR(50) COMMENT '학생 대 교사 비율',
    ACCREDITATION VARCHAR(200) COMMENT '인증 정보',
    RATING DOUBLE COMMENT '평점',
    REVIEW_COUNT INT DEFAULT 0 COMMENT '리뷰 수',
    VIEW_COUNT INT DEFAULT 0 COMMENT '조회수',
    DESCRIPTION TEXT COMMENT '설명',
    IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT '활성 상태',
    IS_PUBLIC BOOLEAN DEFAULT FALSE COMMENT '공립/사립 여부',
    SUBSIDY_AVAILABLE BOOLEAN DEFAULT FALSE COMMENT '보조금 지원 여부',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_facility_code (FACILITY_CODE),
    INDEX idx_facility_type (FACILITY_TYPE),
    INDEX idx_city (CITY),
    INDEX idx_district (DISTRICT),
    INDEX idx_rating (RATING),
    INDEX idx_is_active (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='돌봄시설';

-- Care Facility Booking Table
CREATE TABLE care_facility_bookings (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACILITY_ID BIGINT NOT NULL,
    USER_ID VARCHAR(100) NOT NULL COMMENT '사용자 ID',
    CHILD_NAME VARCHAR(100) NOT NULL COMMENT '자녀명',
    CHILD_AGE INT COMMENT '자녀 나이',
    PARENT_NAME VARCHAR(100) NOT NULL COMMENT '부모명',
    PARENT_PHONE VARCHAR(20) NOT NULL COMMENT '부모 전화번호',
    BOOKING_TYPE VARCHAR(50) NOT NULL COMMENT '예약 유형 (VISIT, REGULAR, TEMPORARY)',
    STATUS VARCHAR(50) NOT NULL COMMENT '예약 상태 (PENDING, CONFIRMED, CANCELLED, COMPLETED)',
    START_TIME DATETIME NOT NULL COMMENT '시작 시간',
    END_TIME DATETIME NOT NULL COMMENT '종료 시간',
    SPECIAL_REQUIREMENTS TEXT COMMENT '특별 요청사항',
    NOTES TEXT COMMENT '메모',
    CANCELLATION_REASON VARCHAR(500) COMMENT '취소 사유',
    CANCELLED_AT DATETIME COMMENT '취소 시간',
    ACTUAL_START_TIME DATETIME COMMENT '실제 시작 시간',
    ACTUAL_END_TIME DATETIME COMMENT '실제 종료 시간',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (FACILITY_ID) REFERENCES TBL_CARE_FACILITIES(ID) ON DELETE CASCADE,
    INDEX idx_facility_id (FACILITY_ID),
    INDEX idx_user_id (USER_ID),
    INDEX idx_status (STATUS),
    INDEX idx_start_time (START_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='돌봄시설 예약';

-- Review Table
CREATE TABLE TBL_REVIEWS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACILITY_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    RATING INT NOT NULL COMMENT '평점 (1-5)',
    CONTENT TEXT COMMENT '리뷰 내용',
    IS_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE COMMENT '검증 여부',
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (FACILITY_ID) REFERENCES TBL_CARE_FACILITIES(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_facility_id (FACILITY_ID),
    INDEX idx_user_id (USER_ID),
    INDEX idx_rating (RATING),
    INDEX idx_is_active (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='돌봄시설 리뷰';

-- ================================================================================
-- 3. Community Domain Tables
-- ================================================================================

-- Post Table
CREATE TABLE TBL_POST (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL COMMENT '게시글 제목',
    CONTENT TEXT COMMENT '게시글 내용',
    AUTHOR_ID BIGINT NOT NULL,
    AUTHOR_NAME VARCHAR(100) COMMENT '작성자명',
    CATEGORY VARCHAR(50) NOT NULL COMMENT '카테고리 (GENERAL, QUESTION, SHARE, REVIEW, NEWS, EVENT, NOTICE)',
    IS_ANONYMOUS BOOLEAN DEFAULT FALSE COMMENT '익명 여부',
    VIEW_COUNT INT DEFAULT 0 COMMENT '조회수',
    LIKE_COUNT INT DEFAULT 0 COMMENT '좋아요 수',
    COMMENT_COUNT INT DEFAULT 0 COMMENT '댓글 수',
    STATUS VARCHAR(50) DEFAULT 'PUBLISHED' COMMENT '상태 (DRAFT, PUBLISHED, HIDDEN, DELETED)',
    IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT '활성 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (AUTHOR_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_author_id (AUTHOR_ID),
    INDEX idx_category (CATEGORY),
    INDEX idx_status (STATUS),
    INDEX idx_created_at (CREATED_AT),
    INDEX idx_is_active (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='게시글';

-- Comment Table
CREATE TABLE TBL_COMMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID BIGINT NOT NULL,
    CONTENT TEXT NOT NULL COMMENT '댓글 내용',
    AUTHOR_ID BIGINT NOT NULL,
    AUTHOR_NAME VARCHAR(100) COMMENT '작성자명',
    LIKE_COUNT INT DEFAULT 0 COMMENT '좋아요 수',
    STATUS VARCHAR(50) DEFAULT 'PUBLISHED' COMMENT '상태',
    IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT '활성 여부',
    PARENT_COMMENT_ID BIGINT COMMENT '부모 댓글 ID (답글)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (POST_ID) REFERENCES TBL_POST(ID) ON DELETE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_COMMENT_ID) REFERENCES TBL_COMMENT(ID) ON DELETE CASCADE,
    INDEX idx_post_id (POST_ID),
    INDEX idx_author_id (AUTHOR_ID),
    INDEX idx_parent_comment_id (PARENT_COMMENT_ID),
    INDEX idx_is_active (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='댓글';

-- Tag Table
CREATE TABLE TBL_TAG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE COMMENT '태그명',
    DESCRIPTION VARCHAR(200) COMMENT '태그 설명',
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_name (NAME),
    INDEX idx_is_active (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='태그';

-- Post-Tag Junction Table (Many-to-Many)
CREATE TABLE TBL_POST_TAGS (
    POST_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL,

    PRIMARY KEY (POST_ID, TAG_ID),
    FOREIGN KEY (POST_ID) REFERENCES TBL_POST(ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TBL_TAG(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='게시글-태그 연결';

-- Post Like Table
CREATE TABLE TBL_POST_LIKE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY uk_post_user (POST_ID, USER_ID),
    FOREIGN KEY (POST_ID) REFERENCES TBL_POST(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_post_id (POST_ID),
    INDEX idx_user_id (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='게시글 좋아요';

-- Bookmark Table
CREATE TABLE TBL_BOOKMARK (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POST_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY uk_post_user (POST_ID, USER_ID),
    FOREIGN KEY (POST_ID) REFERENCES TBL_POST(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_post_id (POST_ID),
    INDEX idx_user_id (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='북마크';

-- ================================================================================
-- 4. Health Domain Tables
-- ================================================================================

-- Hospital Table
CREATE TABLE TBL_HOSPITAL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL COMMENT '병원명',
    TYPE VARCHAR(100) COMMENT '병원 유형 (소아과, 산부인과 등)',
    ADDRESS VARCHAR(500) COMMENT '주소',
    LATITUDE DOUBLE COMMENT '위도',
    LONGITUDE DOUBLE COMMENT '경도',
    PHONE VARCHAR(20) COMMENT '전화번호',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_name (NAME),
    INDEX idx_type (TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='병원';

-- Hospital Like Table
CREATE TABLE TBL_HOSPITAL_LIKE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    HOSPITAL_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY uk_hospital_user (HOSPITAL_ID, USER_ID),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES TBL_HOSPITAL(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_hospital_id (HOSPITAL_ID),
    INDEX idx_user_id (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='병원 좋아요';

-- Hospital Review Table
CREATE TABLE TBL_HOSPITAL_REVIEW (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    HOSPITAL_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    RATING INT NOT NULL COMMENT '평점',
    CONTENT TEXT COMMENT '리뷰 내용',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (HOSPITAL_ID) REFERENCES TBL_HOSPITAL(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_hospital_id (HOSPITAL_ID),
    INDEX idx_user_id (USER_ID),
    INDEX idx_rating (RATING)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='병원 리뷰';

-- Health Record Table
CREATE TABLE TBL_HEALTH_RECORD (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    CHILD_ID BIGINT COMMENT '자녀 ID',
    RECORD_TYPE VARCHAR(50) NOT NULL COMMENT '기록 유형 (VACCINATION, CHECKUP, ILLNESS, GROWTH, DENTAL, EYE, EMERGENCY, OTHER)',
    TITLE VARCHAR(200) NOT NULL COMMENT '제목',
    DESCRIPTION TEXT COMMENT '설명',
    RECORD_DATE DATE NOT NULL COMMENT '기록 날짜',
    NEXT_DATE DATE COMMENT '다음 예정일',
    LOCATION VARCHAR(200) COMMENT '위치',
    DOCTOR_NAME VARCHAR(100) COMMENT '의사명',
    HOSPITAL_NAME VARCHAR(200) COMMENT '병원명',
    HEIGHT DOUBLE COMMENT '키 (cm)',
    WEIGHT DOUBLE COMMENT '몸무게 (kg)',
    TEMPERATURE DOUBLE COMMENT '체온 (°C)',
    BLOOD_PRESSURE VARCHAR(20) COMMENT '혈압 (120/80)',
    PULSE_RATE INT COMMENT '맥박 (회/분)',
    VACCINE_NAME VARCHAR(100) COMMENT '예방접종명',
    VACCINE_BATCH VARCHAR(100) COMMENT '백신 배치번호',
    SYMPTOMS TEXT COMMENT '증상',
    DIAGNOSIS TEXT COMMENT '진단',
    TREATMENT TEXT COMMENT '치료',
    MEDICATION TEXT COMMENT '처방약',
    NOTES TEXT COMMENT '기타 메모',
    STATUS VARCHAR(50) DEFAULT 'COMPLETED' COMMENT '상태 (SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED, MISSED)',
    IS_COMPLETED BOOLEAN DEFAULT FALSE COMMENT '완료 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (CHILD_ID) REFERENCES TBL_CHILD(ID) ON DELETE SET NULL,
    INDEX idx_user_id (USER_ID),
    INDEX idx_child_id (CHILD_ID),
    INDEX idx_record_type (RECORD_TYPE),
    INDEX idx_record_date (RECORD_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='건강기록';

-- Health Record Attachment Table
CREATE TABLE TBL_HEALTH_RECORD_ATTACHMENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    HEALTH_RECORD_ID BIGINT NOT NULL,
    FILE_URL VARCHAR(500) NOT NULL COMMENT '파일 URL',
    FILE_NAME VARCHAR(200) NOT NULL COMMENT '원본 파일명',
    FILE_TYPE VARCHAR(50) COMMENT 'MIME 타입',
    FILE_SIZE BIGINT COMMENT '파일 크기 (바이트)',
    DESCRIPTION VARCHAR(500) COMMENT '첨부파일 설명',
    DISPLAY_ORDER INT NOT NULL DEFAULT 0 COMMENT '표시 순서',
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (HEALTH_RECORD_ID) REFERENCES TBL_HEALTH_RECORD(ID) ON DELETE CASCADE,
    INDEX idx_health_record_id (HEALTH_RECORD_ID),
    INDEX idx_is_active (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='건강기록 첨부파일';

-- ================================================================================
-- 5. Policy Domain Tables
-- ================================================================================

-- Policy Category Table
CREATE TABLE TBL_POLICY_CATEGORIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE COMMENT '카테고리명',
    DESCRIPTION VARCHAR(500) COMMENT '카테고리 설명',
    DISPLAY_ORDER INT NOT NULL DEFAULT 0 COMMENT '표시 순서',
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_name (NAME),
    INDEX idx_is_active (IS_ACTIVE),
    INDEX idx_display_order (DISPLAY_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='정책 카테고리';

-- Policy Table
CREATE TABLE TBL_POLICIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POLICY_CODE VARCHAR(100) NOT NULL UNIQUE COMMENT '정책 코드',
    TITLE VARCHAR(200) NOT NULL COMMENT '정책 제목',
    DESCRIPTION TEXT COMMENT '정책 설명',
    POLICY_TYPE VARCHAR(100) COMMENT '정책 유형',
    TARGET_AGE_MIN INT COMMENT '대상 최소 나이',
    TARGET_AGE_MAX INT COMMENT '대상 최대 나이',
    TARGET_REGION VARCHAR(100) COMMENT '대상 지역',
    BENEFIT_AMOUNT INT COMMENT '지원금액',
    BENEFIT_TYPE VARCHAR(100) COMMENT '지원 유형',
    APPLICATION_START_DATE DATE COMMENT '신청 시작일',
    APPLICATION_END_DATE DATE COMMENT '신청 종료일',
    POLICY_START_DATE DATE COMMENT '정책 시작일',
    POLICY_END_DATE DATE COMMENT '정책 종료일',
    APPLICATION_URL VARCHAR(500) COMMENT '신청 URL',
    CONTACT_INFO VARCHAR(200) COMMENT '연락처',
    REQUIRED_DOCUMENTS TEXT COMMENT '필수 서류',
    IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT '활성 여부',
    PRIORITY INT DEFAULT 0 COMMENT '우선순위',
    CATEGORY_ID BIGINT COMMENT '카테고리 ID',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (CATEGORY_ID) REFERENCES TBL_POLICY_CATEGORIES(ID) ON DELETE SET NULL,
    INDEX idx_policy_code (POLICY_CODE),
    INDEX idx_category_id (CATEGORY_ID),
    INDEX idx_is_active (IS_ACTIVE),
    INDEX idx_target_region (TARGET_REGION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='정책';

-- Policy Document Table
CREATE TABLE TBL_POLICY_DOCUMENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POLICY_ID BIGINT NOT NULL,
    DOCUMENT_URL VARCHAR(500) NOT NULL COMMENT '문서 URL',
    DOCUMENT_TYPE VARCHAR(50) COMMENT '문서 유형',
    FILE_NAME VARCHAR(200) NOT NULL COMMENT '파일명',
    FILE_SIZE BIGINT COMMENT '파일 크기',
    DESCRIPTION VARCHAR(500) COMMENT '문서 설명',
    DISPLAY_ORDER INT NOT NULL DEFAULT 0 COMMENT '표시 순서',
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (POLICY_ID) REFERENCES TBL_POLICIES(ID) ON DELETE CASCADE,
    INDEX idx_policy_id (POLICY_ID),
    INDEX idx_is_active (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='정책 문서';

-- ================================================================================
-- 6. Notification Domain Tables
-- ================================================================================

-- Notification Table
CREATE TABLE TBL_NOTIFICATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    NOTIFICATION_TYPE VARCHAR(50) NOT NULL COMMENT '알림 유형 (POLICY, HEALTH, COMMUNITY, SYSTEM)',
    TITLE VARCHAR(200) NOT NULL COMMENT '알림 제목',
    MESSAGE TEXT NOT NULL COMMENT '알림 메시지',
    IS_READ BOOLEAN NOT NULL DEFAULT FALSE COMMENT '읽음 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_user_id (USER_ID),
    INDEX idx_notification_type (NOTIFICATION_TYPE),
    INDEX idx_is_read (IS_READ),
    INDEX idx_created_at (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='알림';

-- Notification Preference Table
CREATE TABLE notification_preferences (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    NOTIFICATION_TYPE VARCHAR(50) NOT NULL COMMENT '알림 유형',
    EMAIL_ENABLED BOOLEAN NOT NULL DEFAULT TRUE COMMENT '이메일 활성화',
    PUSH_ENABLED BOOLEAN NOT NULL DEFAULT TRUE COMMENT '푸시 활성화',
    SMS_ENABLED BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'SMS 활성화',
    IN_APP_ENABLED BOOLEAN NOT NULL DEFAULT TRUE COMMENT '인앱 활성화',
    EMAIL_ADDRESS VARCHAR(255) COMMENT '이메일 주소',
    PHONE_NUMBER VARCHAR(20) COMMENT '전화번호',
    DEVICE_TOKEN VARCHAR(500) COMMENT '디바이스 토큰',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_user_id (USER_ID),
    INDEX idx_notification_type (NOTIFICATION_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='알림 설정';

-- Notification Template Table
CREATE TABLE TBL_NOTIFICATION_TEMPLATES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEMPLATE_CODE VARCHAR(50) NOT NULL UNIQUE COMMENT '템플릿 코드',
    TITLE VARCHAR(200) NOT NULL COMMENT '알림 제목 템플릿',
    CONTENT TEXT NOT NULL COMMENT '알림 내용 템플릿',
    TEMPLATE_TYPE VARCHAR(50) COMMENT '템플릿 타입 (EMAIL, PUSH, SMS, SYSTEM)',
    DESCRIPTION VARCHAR(500) COMMENT '템플릿 설명',
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE COMMENT '활성 여부',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_template_code (TEMPLATE_CODE),
    INDEX idx_template_type (TEMPLATE_TYPE),
    INDEX idx_is_active (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='알림 템플릿';

-- ================================================================================
-- 7. Chatbot Domain Tables
-- ================================================================================

-- Chat Session Table
CREATE TABLE TBL_CHAT_SESSIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(255) NOT NULL UNIQUE COMMENT '세션 ID',
    USER_ID BIGINT NOT NULL,
    TITLE VARCHAR(200) NOT NULL COMMENT '세션 제목',
    DESCRIPTION VARCHAR(500) COMMENT '세션 설명',
    STATUS VARCHAR(50) NOT NULL COMMENT '세션 상태 (ACTIVE, PAUSED, ENDED)',
    MESSAGE_COUNT INT DEFAULT 0 COMMENT '메시지 수',
    LAST_ACTIVITY_AT DATETIME COMMENT '마지막 활동 시간',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,
    ENDED_AT DATETIME COMMENT '종료 시간',

    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_session_id (SESSION_ID),
    INDEX idx_user_id (USER_ID),
    INDEX idx_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='채팅 세션';

-- Chat Message Table
CREATE TABLE TBL_CHAT_MESSAGES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    MESSAGE VARCHAR(1000) NOT NULL COMMENT '사용자 메시지',
    RESPONSE VARCHAR(2000) NOT NULL COMMENT '챗봇 응답',
    MESSAGE_TYPE VARCHAR(50) NOT NULL COMMENT '메시지 타입 (USER, BOT)',
    INTENT_TYPE VARCHAR(100) NOT NULL COMMENT '의도 타입 (GREETING, QUESTION, COMPLAINT, THANKS, GOODBYE, etc.)',
    CONFIDENCE DOUBLE COMMENT '신뢰도',
    SESSION_ID VARCHAR(255) COMMENT '세션 ID',
    IS_HELPFUL BOOLEAN COMMENT '도움이 되었는지',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID) ON DELETE CASCADE,
    INDEX idx_user_id (USER_ID),
    INDEX idx_session_id (SESSION_ID),
    INDEX idx_created_at (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='채팅 메시지';

-- ================================================================================
-- End of CareCode Database Schema
-- ================================================================================
