-- 정책 변경 이력. 동기화 때 값이 덮어써지면 "무엇이 바뀌었는지" 가 사라져 알림을 만들 수 없다
CREATE TABLE TBL_POLICY_CHANGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POLICY_ID BIGINT NOT NULL,
    CHANGE_TYPE VARCHAR(30) NOT NULL COMMENT 'CREATED / AMOUNT_CHANGED / DEADLINE_CHANGED / TITLE_CHANGED',
    FIELD_NAME VARCHAR(50) COMMENT '바뀐 필드',
    OLD_VALUE VARCHAR(500),
    NEW_VALUE VARCHAR(500),
    TARGET_REGION VARCHAR(200) COMMENT '알림 대상을 고르기 위해 중복 저장한다',
    DETECTED_AT DATETIME NOT NULL,
    NOTIFIED BOOLEAN NOT NULL DEFAULT FALSE COMMENT '알림 발송 여부',
    CONSTRAINT FK_POLICY_CHANGE_POLICY FOREIGN KEY (POLICY_ID)
        REFERENCES TBL_POLICIES (ID) ON DELETE CASCADE
) COMMENT '정책 변경 이력';

-- 미발송 변경만 골라 알림을 보낸다
CREATE INDEX IDX_POLICY_CHANGE_NOTIFIED ON TBL_POLICY_CHANGE (NOTIFIED, DETECTED_AT);
CREATE INDEX IDX_POLICY_CHANGE_POLICY ON TBL_POLICY_CHANGE (POLICY_ID, DETECTED_AT DESC);
