-- 실수령액 제보. 공공데이터는 지원금액을 숫자로 주지 않아 10,964건이 금액 미상이다
-- 받아본 사람만 정확한 금액을 안다. 여러 명이 같은 값을 내면 수기 검증에 준하는 신뢰도가 된다
CREATE TABLE TBL_BENEFIT_AMOUNT_REPORT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POLICY_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    REPORTED_AMOUNT INT NOT NULL COMMENT '실제 수령액(원)',
    PAYMENT_TYPE VARCHAR(20) NOT NULL COMMENT 'MONTHLY / ONE_TIME',
    RECEIVED_AT DATE COMMENT '수령 시점',
    NOTE VARCHAR(300),
    CREATED_AT DATETIME NOT NULL,
    -- 한 사람이 같은 정책을 여러 번 제보하면 표본이 왜곡된다
    CONSTRAINT UK_BENEFIT_REPORT_USER UNIQUE (POLICY_ID, USER_ID),
    CONSTRAINT FK_BENEFIT_REPORT_POLICY FOREIGN KEY (POLICY_ID)
        REFERENCES TBL_POLICIES (ID) ON DELETE CASCADE,
    CONSTRAINT FK_BENEFIT_REPORT_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (ID) ON DELETE CASCADE
) COMMENT '지원금 실수령액 제보';

CREATE INDEX IDX_BENEFIT_REPORT_POLICY ON TBL_BENEFIT_AMOUNT_REPORT (POLICY_ID, REPORTED_AMOUNT);
