-- 대기 기록. 정원 관측만으로는 "실제로 얼마나 기다렸는지" 를 알 수 없다
-- 이 데이터는 공공데이터에 존재하지 않아 사용자에게서만 얻을 수 있다
CREATE TABLE TBL_FACILITY_WAITLIST (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACILITY_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CHILD_ID BIGINT NOT NULL,
    WAIT_NUMBER INT COMMENT '대기 순번',
    APPLIED_AT DATE NOT NULL COMMENT '대기 신청일',
    STATUS VARCHAR(20) NOT NULL COMMENT 'WAITING / ADMITTED / GAVE_UP',
    RESOLVED_AT DATE COMMENT '입소일 또는 포기일',
    CLASS_AGE INT COMMENT '신청 당시 아이 월령',
    NOTE VARCHAR(300),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    -- 같은 아이가 같은 시설에 중복 등록되면 통계가 왜곡된다
    CONSTRAINT UK_WAITLIST_CHILD_FACILITY UNIQUE (FACILITY_ID, CHILD_ID),
    CONSTRAINT FK_WAITLIST_FACILITY FOREIGN KEY (FACILITY_ID)
        REFERENCES TBL_CARE_FACILITIES (ID) ON DELETE CASCADE,
    CONSTRAINT FK_WAITLIST_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_WAITLIST_CHILD FOREIGN KEY (CHILD_ID)
        REFERENCES TBL_CHILD (ID) ON DELETE CASCADE
) COMMENT '어린이집 대기 기록';

-- 시설별 실제 대기 기간 통계
CREATE INDEX IDX_WAITLIST_FACILITY_STATUS ON TBL_FACILITY_WAITLIST (FACILITY_ID, STATUS);
CREATE INDEX IDX_WAITLIST_USER ON TBL_FACILITY_WAITLIST (USER_ID, STATUS);
