-- 마감 임박 알림 발송 이력.
-- "남은 일수가 D-7 인 날에만 보낸다" 는 규칙만으로는 하루에 여러 번 실행될 때를 막지 못한다.
-- 배포가 Blue/Green 이라 인스턴스가 잠깐 2대가 되면 모든 알림이 두 번씩 나간다.
-- 유니크 제약이 그 상황에서도 한 번만 남게 만든다.

CREATE TABLE TBL_POLICY_DEADLINE_NOTICE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    POLICY_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    NOTIFIED_ON DATE NOT NULL COMMENT '발송한 날짜',
    DAYS_LEFT INT NOT NULL COMMENT '발송 시점의 잔여 일수',
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT UK_POLICY_DEADLINE_NOTICE UNIQUE (POLICY_ID, USER_ID, NOTIFIED_ON),
    CONSTRAINT FK_POLICY_DEADLINE_NOTICE_USER FOREIGN KEY (USER_ID)
        REFERENCES TBL_USER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_POLICY_DEADLINE_NOTICE_POLICY FOREIGN KEY (POLICY_ID)
        REFERENCES TBL_POLICIES (ID) ON DELETE CASCADE
) COMMENT '마감 임박 알림 발송 이력';
