-- 시설 정원·현원 시계열. 동기화 때마다 현원을 덮어쓰면 관측 이력이 사라져 입소 가능 시점을 예측할 수 없다
CREATE TABLE TBL_FACILITY_CAPACITY_SNAPSHOT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACILITY_ID BIGINT NOT NULL COMMENT '시설 ID',
    OBSERVED_DATE DATE NOT NULL COMMENT '관측일 (동기화 실행일)',
    CAPACITY INT COMMENT '정원',
    CURRENT_ENROLLMENT INT COMMENT '현원',
    AVAILABLE_SPOTS INT COMMENT '잔여석 (정원 - 현원)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 같은 날 재동기화해도 행이 늘지 않도록 (시설, 관측일) 을 고유키로 둔다.
    CONSTRAINT UK_FACILITY_SNAPSHOT_DATE UNIQUE (FACILITY_ID, OBSERVED_DATE),
    CONSTRAINT FK_SNAPSHOT_FACILITY FOREIGN KEY (FACILITY_ID)
        REFERENCES TBL_CARE_FACILITIES (ID) ON DELETE CASCADE
) COMMENT '시설 정원 변동 관측 이력';

-- 예측은 항상 "특정 시설의 기간별 추이" 로 조회하므로 이 순서가 맞다.
CREATE INDEX IDX_SNAPSHOT_FACILITY_DATE
    ON TBL_FACILITY_CAPACITY_SNAPSHOT (FACILITY_ID, OBSERVED_DATE DESC);

-- 전국 단위 집계(지역별 여석률 등) 용
CREATE INDEX IDX_SNAPSHOT_DATE
    ON TBL_FACILITY_CAPACITY_SNAPSHOT (OBSERVED_DATE);
