-- 사용자 행동 이벤트. 전환율·리텐션을 사후에 계산할 수 있게 원본을 남긴다
CREATE TABLE TBL_USER_EVENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NULL COMMENT '비로그인 이벤트는 NULL',
    EVENT_TYPE VARCHAR(60) NOT NULL COMMENT '이벤트 종류',
    TARGET_ID VARCHAR(100) NULL COMMENT '대상 식별자 (정책 ID, 시설 ID 등)',
    METADATA VARCHAR(500) NULL COMMENT '부가 정보 (JSON)',
    OCCURRED_AT DATETIME NOT NULL,
    OCCURRED_DATE DATE NOT NULL COMMENT '일 단위 집계용 — 리텐션 쿼리가 매번 DATE() 를 쓰면 인덱스를 못 탄다'
) COMMENT '사용자 행동 이벤트 로그';

-- 퍼널: 특정 이벤트의 기간별 사용자 수
CREATE INDEX IDX_EVENT_TYPE_DATE ON TBL_USER_EVENT (EVENT_TYPE, OCCURRED_DATE);
-- 리텐션: 사용자별 활동일
CREATE INDEX IDX_EVENT_USER_DATE ON TBL_USER_EVENT (USER_ID, OCCURRED_DATE);
