-- 정책 금액 검증 이력. 틀린 금액을 확정치처럼 보여주면 신뢰 문제를 넘어 분쟁이 된다
ALTER TABLE TBL_POLICIES
    ADD COLUMN VERIFIED_AT DATETIME NULL COMMENT '수기 검증 시각 - NULL 이면 미검증(추정치)';

ALTER TABLE TBL_POLICIES
    ADD COLUMN VERIFIED_BY VARCHAR(100) NULL COMMENT '검증자';

ALTER TABLE TBL_POLICIES
    ADD COLUMN SOURCE_URL VARCHAR(500) NULL COMMENT '금액 근거 출처';

-- 지역별 검증률 집계용
CREATE INDEX IDX_POLICIES_REGION_VERIFIED ON TBL_POLICIES (TARGET_REGION, VERIFIED_AT);
